stages:
  - coverage
  - sonarqube-check

coverage:
  stage: coverage
  tags:
    - compcs140
  image:
    name: "maven:3.6.3-openjdk-11"
  script:
    - cd Sisu
    - mvn compile
    - mvn test
  artifacts:
    paths:
    - Sisu/target/classes
    expire_in: 30 mins


sonarqube-check:
  stage: sonarqube-check
  tags:
    - compcs140
  image:
    name: "sonarsource/sonar-scanner-cli:4.3"
    entrypoint: [""]
  dependencies:
    - coverage
  script:
    - sonar-scanner -Dsonar.projectKey=$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME -Dsonar.java.binaries=target/classes -Dsonar.java.test.binaries=target/test-classes -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml -Dsonar.tests=src/test -Dsonar.sources=src/main/main/java/fi/tuni/prog3/sisu
  only:
    refs:
      - main

